dataset_dir: /home/macy/Data/DCASE20/dataset_dir
model_dir: ./mymodel
spec_dir: ../../spec
log_dir: ./log

mt:
  train: ['ToyCar']
  test: ['ToyCar']

train_set: 'deval'  # 'dev', 'eval', 'deval'

feat:
  spec: 'mel'
  fft_num: 2048
  mel_bin: 128
  frame_hop: 512
  frame_num: 128
  graph_hop_f: 1

net:
  act: ['leakyrelu', 'relu']  # Encoder, Decoder
  normalize: {'d':'ln', 'g': 'ln'}
  nz: 256
  ndf: 32
  ngf: 32
  isize: 128

train:
  lrD: 0.0002
  lrG: 0.0002
  beta1: 0.5
  epoch: 75
  bs: 512
  wgan:
    feat_match_eff: 1
    match_item: {'mu': 1, 'sigma': 1}  # 'mu': 1, 'sigma': 1
    ncritic: 1
    lambda_gp: 10  # for gradient penalty

detect:
  p: 0.1

repre:
  normal: 0
  anomaly: 1

#epoch 49: [recon: 3.2896e-03] [d2g: 3.1875e-04] [gloss: 3.6084e-03] [best: 0.8595] [time: 4807s]
#ToyCar: [AUC: 0.9158] [pAUC: 0.7783] [aver: 0.8471] [metric: D_maha]